title: "Reeva Faisal" 

# description: > 
#   Senior studying Data Science at the University of Michigan - Ann Arbor
logo: "assets/Screenshot 2024-10-13 at 4.04.46 PM_batcheditor_fotor (1).jpg"
email: reevaf@umich.edu
# theme: jekyll-theme-minimal
favicon: true 
plugins: 
  - jekyll-remote-theme

# plugins:
#   - jekyll-sitemap  
#   - jekyll-seo-tag
#   - jemoji
# color-scheme: light

# remote_theme: reevafaisal/hexo-theme-edinburgh
remote_theme: reevafaisal/jekyll-theme-minimal-new

# editor.find.cursorMoveOnType: false
navigation:
  - name: Introduction
    link: ./index.html#introduction
  - name: Projects
    link: ./index.html#projects
