title: "Reeva Faisal" 

description: > 
  Senior studying Data Science at the University of Michigan - Ann Arbor
  Undergraduate researcher at <a href="https://neurocy.notion.site/Future-of-Programming-Lab-241d162461a04064ae1fd9ae32bf4cb1">Future of Programming Lab</a>
logo: "assets"
email: reevaf@umich.edu
# theme: jekyll-theme-minimal
favicon: true 
plugins: 
  - jekyll-remote-theme

# plugins:
#   - jekyll-sitemap  
#   - jekyll-seo-tag
#   - jemoji
# color-scheme: light

# remote_theme: reevafaisal/hexo-theme-edinburgh
remote_theme: reevafaisal/jekyll-theme-minimal-new

# editor.find.cursorMoveOnType: false
navigation:
  - name: Introduction
    link: ./index.html#introduction
  - name: Projects
    link: ./index.html#projects
