title: "Reeva Faisal" 

# description: > 
#   Senior studying Data Science at the University of Michigan - Ann Arbor
logo: "assets/Screenshot 2024-10-13 at 4.04.46 PM_batcheditor_fotor (1).jpg"
email: reevaf@umich.edu
# theme: jekyll-theme-minimal
favicon: true 
plugins: 
  - jekyll-remote-theme

# plugins:
#   - jekyll-sitemap  
#   - jekyll-seo-tag
#   - jemoji
color-scheme: light

# remote_theme: reevafaisal/hexo-theme-edinburgh
remote_theme: reevafaisal/jekyll-theme-minimal-new

# editor.find.cursorMoveOnType: false
navigation:
  - name: Introduction
    link: ./index.html#introduction
  - name: Publications and Presentations
    link: ./index.html#publications-and-presentations
  - name: Projects
    link: ./index.html#projects
    sublist:
    - name: Weather Patterns Forecasting & Anomaly Detection
      link: ./index.html#weather-patterns-time-series-forecasting-and-anomaly-detection
    - name: Search Engine
      link: ./index.html#search-engine
    - name: Mortality Outcome Prediction in TB and HIV
      link: ./index.html#mortality-outcome-prediction-in-tb-and-hiv
    - name: MapReduce Framework
      link: ./index.html#mapreduce-framework
    - name: Insta485 Client-Side Web Application
      link: ./index.html#insta485-client-side-web-application
    - name: Travelling Salesman Problem
      link: ./index.html#travelling-salesman-problem
